### ISSUE TITLE
On Category listing, Increase individual book title size, plus title description, “excerpt” copy

### ISSUE THREAD

**Issue by RobKelley** [NYPL-Simplified/web-reader-landing-page#108]

**Comment by kendraralston** [comment]
The category "Tales from around the world" is too long for mobile view? This needs to be shortened.

**Comment by EdwinGuzman** [comment]
@ricardoom can this be closed?

**Comment by kendraralston** [comment]
"excerpt" copy updated to:

Full Book
Book Excerpt
Short Reads

**Comment by EdwinGuzman** [comment]
The copy has been updated.

@ricardoom can this be closed for the other issues?
