### ISSUE TITLE
Align the look of the button and learn more links more closely to design

### ISSUE THREAD

**Issue by RobKelley** [NYPL-Simplified/web-reader-landing-page#109]
(bold words, letterspaced slightly, image bracket instead of typed bracket)

**Comment by EdwinGuzman** [comment]
@ricardoom I think most of the recent deployment to QA covers this.

**Comment by EdwinGuzman** [comment]
@ricardoom I think this can be closed now. Update is on prod now.

**Comment by ricardoom** [comment]
closing
