### ISSUE TITLE
Update Book Details page (design)

### ISSUE THREAD

**Issue by RobKelley** [NYPL-Simplified/web-reader-landing-page#110]
*  Increase individual book title size, plus title description, “excerpt” copy
* Make equal the Space on either side of share buttons
* Increase font size for the book description
* Align start reading button more closely to design (same edits that were made to buttons on Category level page)
* Make the title of book and book jacket also link to the reading experience? people often click names or pictures)

**Comment by EdwinGuzman** [comment]
@ricardoom can this be closed?

**Comment by ricardoom** [comment]
:thinking:

**Comment by ricardoom** [comment]
Only thing needs doing is linking up the `img` on the details screen to go to  the book. the other design issues fine.

**Comment by EdwinGuzman** [comment]
I think we said we would not do that? I can update that though, yes?

**Comment by ricardoom** [comment]
if not then we can close.
