### ISSUE TITLE
Update to nicer urls

### ISSUE THREAD

**Issue by EdwinGuzman** [NYPL-Simplified/web-reader-landing-page#115]
@aslagle I'd like to:
* rename `/book_desc/...` to `/book/...`.
* update category urls from `category/Mysteries%20&%20Suspense.html` to `category/mysteries-suspense.html`

**Comment by aslagle** [comment]
:+1:

the reader is also under `/books/...`

**Comment by EdwinGuzman** [comment]
Do you think we should update that?

Also, for context, want to update the category urls to validate: https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fd210qhkuica97m.cloudfront.net%2F

**Comment by aslagle** [comment]
I think it's fine, do you have a better idea for where to put it?

**Comment by EdwinGuzman** [comment]
`/books/` is good.
