### ISSUE TITLE
Update Legal Copy

### ISSUE THREAD

**Issue by jce1028** [NYPL-Simplified/web-reader-landing-page#117]

**Comment by jce1028** [comment]
Terms of Use

Please read this Terms of Use, the NYPL's Terms and Conditions [https://www.nypl.org/help/about-nypl/legal-notices/website-terms-and-conditions] and the NYPL's Privacy Policy [insert link] before using any aspect of the Subway Library (the "Agreement"). By using this website, you agree to be bound by the following and all of the Agreement.  

Use of Content. Upon your download or access of digital content, such as books, newspapers, magazines, and other content ("Content"), the parties offering Content ("Content Provider") grants you a free, non-exclusive right to view, use, and display such Content an unlimited number of times, solely through subwaylibrary.com, SimplyE app or as otherwise permitted, solely on your supported mobile device, and solely for your personal, non-commercial use during the Subway Library Campaign. Content is licensed, not sold, to you by the Content Provider. The Content Provider may include additional terms for use within its Content. Those terms will also apply, but this Terms of Use will govern in the event of a conflict.

Limitations. Unless specifically indicated otherwise, you may not sell, rent, lease, distribute, broadcast, sublicense, or otherwise assign any rights to the Content or any portion of it to any third party, and you may not remove or modify any proprietary notices or labels on the Content. In addition, you may not attempt to bypass, modify, defeat, or otherwise, circumvent any digital rights management system or other content protection or features used to protect the Content.

Termination. Your rights under this Agreement will automatically terminate if you fail to comply with any term of this Agreement. In case of such termination, you must cease all use of the Content, and NYPL may immediately revoke your access.

**Comment by EdwinGuzman** [comment]
Are we switching from "Terms and Conditions" to "Terms of Use"? Does that mean you want a page within Subway Library with this copy instead of linking to NYPL's "Terms and Conditions"? @jce1028

**Comment by jce1028** [comment]
Correct, "Terms of Use"
