### ISSUE TITLE
[All pages] Use %, em to specify font size

### ISSUE THREAD

**Issue by wlla** [NYPL-Simplified/web-reader-landing-page#124]
[All pages] Use %, em instead of pt/px to specify font size

Source: Cynthiasays is throwing an error

**Comment by EdwinGuzman** [comment]
I don't see this error on the qa homepage http://qa.subwaylibrary.com/ ...

@ricardoom and I are going to be using rem (which is similar to em) for font-sizes, but the base font size for the `html` element will be 16px. That update shouldn't throw an error as it's currently set to 12px and there's no error.
