### ISSUE TITLE
[Genre page] Genre microcopy

### ISSUE THREAD

**Issue by wlla** [NYPL-Simplified/web-reader-landing-page#125]
In Genre pages, consider rewording “LEARN MORE” to “VIEW BOOK RECORD” or “READ DESCRIPTION” or something more descriptive.

Content call.

**Comment by EdwinGuzman** [comment]
@kendraralston

**Comment by kendraralston** [comment]
READ SUMMARY

**Comment by kendraralston** [comment]
I forgot read was already there. Can you update to "VIEW SUMMARY" ?

**Comment by EdwinGuzman** [comment]
The aria-label for the "LEARN MORE" (which will be updated to "VIEW SUMMARY") button currently is set to "Learn more about [title of book]". Think that should also be updated to "View summary of [title of book]." ? @wlla @kendraralston

**Comment by kendraralston** [comment]
Yes! Thanks.
