### ISSUE TITLE
Love Stories title

### ISSUE THREAD

**Issue by johneedutton** [NYPL-Simplified/web-reader-landing-page#135]
http://qa.subwaylibrary.com/category/Love%20stories.html

Initial caps - Love Stories not Love stories

**Comment by EdwinGuzman** [comment]
Those titles get pulled in from the spreadsheet, so the titles need to be updated there. @kendraralston is working on this issue with Reader Services.

**Comment by jce1028** [comment]
This category will not be in the final.
