### ISSUE TITLE
Remove empty id attribute from Transit Wireless logo SVG

### ISSUE THREAD

**Issue by seanredmond** [NYPL-Simplified/web-reader-landing-page#145]
The Transit Wireless logo has a `title` with an empty `id`. Just delete the attribute. 

    <svg xmlns="http://www.w3.org/2000/svg" width="384.83016" height="127.68614" viewBox="0 0 384.83016 127.68614">
         <title id="">transitWifi</title>
          ...
     </svg>

**Comment by EdwinGuzman** [comment]
@jce1028 this is also being reviewed in #186 .
