### ISSUE TITLE
Enforce additional restrictions on featured titles

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/web-reader-landing-page#154]
For each lane, a set of ten featured titles is randomly selected to be shown on the front page. 

```
              # randomize books in lane, each build
              random.shuffle(mta_category_dict[category_key]["home"])

              #pluck first 10
              shortenHomeLane = (mta_category_dict[category_key]["home"])[:10]
```

Reader Services has requested a few changes to this:

1. Present the books in the same order they appear in the "RS Selections" spreadsheet.
2. Restrict the choices to include at least one title from every commercial publisher that has a featured book in that lane. (This way Reader Services doesn't have to carefully enforce this restriction themselves.)

**Comment by leonardr** [comment]
We've talked it over and decided that #2 is too much work for the time we have left. It will be Reader Services' responsibility to make sure that the commercial publishers don't feel snubbed.

**Comment by nodanaonlyzuul** [comment]
I'll take this on (scoped down to the first bullet point).
