### ISSUE TITLE
Header is skewed in Desktop (IE 11)

### ISSUE THREAD

**Issue by RobKelley** [NYPL-Simplified/web-reader-landing-page#158]
The logo and buttons are misaligned in this view.

**Comment by RobKelley** [comment]
![too](https://cloud.githubusercontent.com/assets/145462/25670122/a75157ca-2ff9-11e7-905e-e80372dbd4d4.png)

**Comment by EdwinGuzman** [comment]
@ricardoom do you think most of this will get fixed when we add a normalize css file? If so, we can check this issues after we add it instead of trying to fix it first.

**Comment by ricardoom** [comment]
🍖  @EdwinGuzman ¿quien sabe? i'd say thats a good place to start... but for now... 💤
