### ISSUE TITLE
Add a robots.txt no follow directive to hide us from SEO

### ISSUE THREAD

**Issue by RobKelley** [NYPL-Simplified/web-reader-landing-page#184]
Crawlers should not be able to get down into the site.  It's a risk with publishers 

James has approved.

**Comment by nodanaonlyzuul** [comment]
Do you want to hide the entire site with a robots.txt that reads?:

```
User-agent: *
Disallow: /
```

**Comment by RobKelley** [comment]
@jce1028 @leonardr  I assume we want to hide the whole site, since the homepage itself has crawlable titles and images.   

Let us know if your think otherwise

**Comment by leonardr** [comment]
The whole site is transient, and hiding it is the simplest thing to do, so I say hide the whole thing.
