### ISSUE TITLE
Limit access to the United States

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/web-reader-landing-page#191]
To keep publishers happy we have agreed to limit access to users who visit from with the United States. (I don't know if we agreed to this as part of a formal legal agreement, but it doesn't matter for purposes of this issue.)

It should be possible to configure CloudFront and/or S3 to only deliver resources to IPs located within the United States.

**Comment by nodanaonlyzuul** [comment]
Okay. 
I've whitelisted QA and production to be whitelisted to the US.
It'll probably take ~30 minutes to propagate.
Happy to keep this ticket open until we verify by asking a kind stranger abroad to test.

![geo-restriction](https://cloud.githubusercontent.com/assets/8731/25749986/6b6c15b6-317e-11e7-8341-2ecdcf013ecf.gif)

**Comment by leonardr** [comment]
My sister lives in the UK. I had her confirm that the site is not accessible.

_The request could not be satisfied.

The Amazon CloudFront distribution is configured to block access from your country._

Maybe the error message could be more friendly, but the basic functionality is satisfied.

**Comment by nodanaonlyzuul** [comment]
Great. I'll close this and we can revisit nicer errors if / when it becomes a priority.
