### ISSUE TITLE
Add revised Privacy Policy language

### ISSUE THREAD

**Issue by jce1028** [NYPL-Simplified/web-reader-landing-page#195]
The New York Public Library’s SimplyE app makes it easy for you to access more than 120,000 free ebook titles in just a few short steps. SimplyE is consistent with NYPL’s privacy policy, which can be found at http://www.nypl.org/help/about-nypl/legal-notices/privacy-policy. We encourage you to read it carefully.  NYPL will not share your Personal Information but we will be sharing overall usage data with third-party providers who help NYPL deliver e-book content.

**Comment by kendraralston** [comment]
A couple of notes:

- (per editorial style guide) I'd recommend linking the URL to the words: NYPL's privacy policy 
- 'Personal Information' doesn't need to be capitalized
- change "but we will be sharing" to "but will share"

**Comment by EdwinGuzman** [comment]
@jce1028 Leaving the link written out as is, but what do you think of the other two notes from @kendraralston ?

**Comment by EdwinGuzman** [comment]
Leaving content as is for now.
