### ISSUE TITLE
footer logos not rendering on Android 4.3 

### ISSUE THREAD

**Issue by jbdalton** [NYPL-Simplified/web-reader-landing-page#204]
We're not seeing the logos in the footer when loading on devices running OS's based on Android 4.3.  

So far while running Browserstack automated tests of basic functionality, I've seen this on Samsung Note 3 and Kindle Fire HDX 7.    The newer Kindle Fire HD 10 in Room 200 does not have this problem.  It is running an OS based  on Android 5.

example for Samsung Note 3:

![qa_check_browse_functions_no_menu_spec_scroll_footer_android_samsung_galaxy_note_3_android_20170508_133906_602](https://cloud.githubusercontent.com/assets/1854259/25820412/2b01dc76-33ff-11e7-8347-3df16dca26fc.png)

**Comment by EdwinGuzman** [comment]
@ricardoom this will be fun.

**Comment by EdwinGuzman** [comment]
@jbdalton can you review the About page on the same device/browser? Some of the footer logos appear at the top of the About page.

**Comment by jbdalton** [comment]
It has the same problem on the About Page.

![screenshot-samsung-note-3-1f493801ea](https://cloud.githubusercontent.com/assets/1854259/25821479/3a620f02-3403-11e7-87b3-945b2e04e692.jpeg)

**Comment by EdwinGuzman** [comment]
Should be fixed.  The layout is wonky but it's as good as it'll get without me putting more time on it. Can you verify the:
* footer
* about page
* the START READING button

I'll make a PR after it looks good.

![image1 2](https://cloud.githubusercontent.com/assets/1280564/25869526/9e794016-34ce-11e7-893b-9643d51623cb.JPG)

**Comment by jbdalton** [comment]
browserstack has it passing on Android 4.3 and 4.4 when viewed against a REAL device on their device farm.  The BS emulator still has trouble w/, for example, 4.2-4 (like Samsung Note 3) but that same page using their real-device farm on Note 3 looks fine.  They don't have alot of other Android 4.3 real-device connections, and none for 4.2.

I think it's safe to assume that their emulator is pretty wonky on the older Android versions, which I have seen other evidence of,  so in my opinion we canclose this ticket on Android 4.2 (checked on our own hardware) and Android 4.3-4 (checked on BS real-device farm).

**Comment by EdwinGuzman** [comment]
Great! Thanks for checking! I'll make a note of that in the PR.
