### ISSUE TITLE
Nicer Error Message For People outside US.

### ISSUE THREAD

**Issue by nodanaonlyzuul** [NYPL-Simplified/web-reader-landing-page#206]
Because of rights restrictions...content is fenced to within the US (https://github.com/NYPL-Simplified/web-reader-landing-page/issues/191):
It works! But its a default CloudFront error. **Let's investigate making it more humane.**

[Amazon's Documentation](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/georestrictions.html) has this example:

> Here's how geo restriction works:
> 
> Suppose you have rights to distribute your content only in Liechtenstein. You update your CloudFront web distribution and add a whitelist that contains only Liechtenstein. (Alternatively, you could add a blacklist that contains every country except Liechtenstein.)
> 
> A user in Monaco requests your content, and DNS routes the request to the CloudFront edge location in Milan, Italy.
> 
> The edge location in Milan looks up your distribution and determines that the user in Monaco is not allowed to download your content.
> 
> CloudFront returns an HTTP status code of 403 (Forbidden) to the user.
> 
> You can optionally configure CloudFront to return a custom error message to the user, and you can specify how long you want CloudFront to cache the error response for the requested object; the default value is five minutes. For more information, see Customizing Error Responses.

**Comment by nodanaonlyzuul** [comment]
Hey Great.

We've confirmed that a user in UK got a custom error when trying to access the site.
From cloudfront's point of view, all I had to do was make a custom error response like
the one in this spreadsheet.

![screen shot 2017-05-08 at 2 37 19 pm](https://cloud.githubusercontent.com/assets/8731/25856939/83c428d6-34a5-11e7-947d-543fb96230cd.png)

**Comment by nodanaonlyzuul** [comment]
@EdwinGuzman and @courtneymcgee - I'm going to assign this ticket to you for design and copy.
All you need to do is add 403.html to the root output folder.

**Comment by EdwinGuzman** [comment]
@courtneymcgee The page will look similar to https://subwaylibrary.com/404.html . Let me know what you want to display there.

**Comment by courtneymcgee** [comment]
@EdwinGuzman - Here ya go:

We’re sorry… 

Subway Library titles are not available in your country. 

Visit the Subway Library [home page](https://subwaylibrary.com/) or [learn more about SimplyE](https://www.nypl.org/books-music-dvds/ebookcentral/simplye).
