### ISSUE TITLE
Add meta tag to reader for running in full screen mode when saved to home screen

### ISSUE THREAD

**Issue by aslagle** [NYPL-Simplified/web-reader-landing-page#28]

**Comment by aslagle** [comment]
Also, we should probably turn off user-scalable.

**Comment by ricardoom** [comment]
so we use:
````<meta name="viewport" content="width=device-width, initial-scale=1">````
?

**Comment by aslagle** [comment]
Unfortunately Apple disabled "user-scalable=no" in iOS 10.
