### ISSUE TITLE
add "A" to incrementor / decrementor

### ISSUE THREAD

**Issue by ricardoom** [NYPL-Simplified/web-reader-landing-page#30]
For the font sizing change control, It would be great if the "A" could be added between the [-] A [+] controls. it would also be great if that  was subject to size change as well, so as you increase or decrease the "A" changes size as well... But initially we should get the A in there first.

I suppose it should be on the ```mta-style``` branch

![screen shot 2017-04-24 at 11 27 58 am](https://cloud.githubusercontent.com/assets/20174701/25345348/db79c690-28e2-11e7-8b30-75290a9a606f.png)

**Comment by aslagle** [comment]
on mta-style branch
