### ISSUE TITLE
CloudFront Encoding Issue?

### ISSUE THREAD

**Issue by kfriedman** [NYPL-Simplified/web-reader-landing-page#34]
Is there a CloudFront encoding issue? The following URL does not load from CloudFront:

https://d210qhkuica97m.cloudfront.net/book_desc/Monsieur%20Lecoq%20-%20%C3%89mile%20Gaboriau.html

Yet, the corresponding URL seems to load from the S3 bucket:

https://s3.amazonaws.com/subway-reading-2017-qa/book_desc/Monsieur+Lecoq+-+E%CC%81mile+Gaboriau.html

**Comment by kfriedman** [comment]
Seems like there's another URL with a problem:
https://d210qhkuica97m.cloudfront.net/book_desc/The%20Spy%20-%20C%C3%A9sar%20Aira.html

**Comment by nodanaonlyzuul** [comment]
Closing this issue since https://github.com/NYPL-Simplified/web-reader-landing-page/pull/53 has been merged in and fixes this.
