### ISSUE TITLE
Add accessible text to menu buttons

### ISSUE THREAD

**Issue by seanredmond** [NYPL-Simplified/web-reader-landing-page#35]
`#menu-button-open` and `#menu-button-close` need labelling or visually hidden content.

**Comment by ricardoom** [comment]
can we do ````aria-labelledby```` or ````aria-label```` for some reason the ````visually-hidden```` classes bug me... seems easier to keep track & separate concerns for ````a11y```` functionality to have the aria attributes instead of mixing visual styling up w/ a11y function

**Comment by seanredmond** [comment]
The super lucky happy time gold medal goes to pages that render nicely in Lynx, and you need visually hidden text for that. Aria-label gets slightly less gold if we want to save visually hidden text for text we might want to unhide.

**Comment by ricardoom** [comment]
womp womp... ¯\_(ツ)_/¯
