### ISSUE TITLE
Border in book selection overlaps the first character of adjacent first lane titles.

### ISSUE THREAD

**Issue by aslagle** [NYPL-Simplified/web-reader-landing-page#37]
Moved from https://github.com/NYPL-Simplified/webpub-viewer/issues/56

But only seems to occur in the 1st lane (Mysteries & Suspense on my reader).

Device: iOS 10.3
phone: IPhone 6

https://cloud.githubusercontent.com/assets/1854259/25395448/0df0b3f0-29af-11e7-9e82-49f45b6b6c10.PNG

**Comment by EdwinGuzman** [comment]
Temporarily removed the focus per @ricardoom . We'll get something in soon.
