### ISSUE TITLE
Incorporate "MTA Titles from Publishers" spreadsheet into pipeline

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/web-reader-landing-page#43]
Reader Services appears to be putting information we get from publishers into this document:

https://docs.google.com/spreadsheets/d/1khckI94V3Q0a7ZMZvaniieuZYavRN9TnkGTwwgQxX6g/edit?ts=59009eb9#gid=0

The spreadsheet currently lists titles from HarperCollins. Items selected by Reader Services are highlighted.

It's not clear how or at what point this will happen, but at some point the selected rows need to be converted into the format used by the main "RS MTA Selections" spreadsheet, and copied over there.

https://docs.google.com/spreadsheets/d/1TNykdmeY2zYOvWRcn46YBrF6ar31ZbLVzZANSoKASNk/edit?ts=58ece1d2#gid=0

**Comment by nodanaonlyzuul** [comment]
For posterity - this should be closed once I get usable HC information into the "Master Metadata List" spreadsheet.

**Comment by jce1028** [comment]
Request for fixes to HC meta data sent.

**Comment by nodanaonlyzuul** [comment]
I've put the HC titles into the metadata spreadsheet.
