### ISSUE TITLE
Update placeholder pages

### ISSUE THREAD

**Issue by EdwinGuzman** [NYPL-Simplified/web-reader-landing-page#47]
For the "privacy policy" and "terms and conditions". Also verify the order of those footer links.

**Comment by RobKelley** [comment]
link inside privacy policy has typo, trailing l:   http://www.nypl.org/help/about-nypl/legal-notices/privacy-policyl

I assume it also needs stylesheet applied.

**Comment by RobKelley** [comment]
privacy and https://d210qhkuica97m.cloudfront.net/license.html also has funky in-line styling @ricardoom

**Comment by ricardoom** [comment]
removing the `<style>...</style>` at the top and replacing w/ our style sheet should get us most of the way there... removing the inline styles should probably wait, I can do it so @EdwinGuzman can focus on more important tasks if need be...

**Comment by EdwinGuzman** [comment]
Mentioned on slack but want to mention it here too: No need to update the placeholder pages just yet.

**Comment by RobKelley** [comment]
ok, signoff from Bridget and James (via email I forwarded). 

 when you;re ready: 

1 Terms and Conditions should just link to: https://www.nypl.org/help/about-nypl/legal-notices/website-terms-and-conditions
2. Privacy Policy copy is fine (with corrected link)
