### ISSUE TITLE
Add flag for featurable content

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/web-reader-landing-page#62]
New column in the spreadsheet. If there's a value in this column, the book can be selected to represent its lane(s) on the main page. If not, the book shows up in the big list of all books in that lane, but it never shows up on the main page.

**Comment by nodanaonlyzuul** [comment]
For posterity....

* On the catalog page, books within a row will have their order randomized each build.
* Whether or not a book shows up in that row is based on this a new "Featurable" column in the spreadsheet.
* On a category page, all books in that category show up, in alphabetical order by title.

**Comment by nodanaonlyzuul** [comment]
Titles being sorted on the category page has been merged in via:
https://github.com/NYPL-Simplified/web-reader-landing-page/pull/79

**Comment by nodanaonlyzuul** [comment]
This is complete / done / merged into master.
