### ISSUE TITLE
Update cache manifest

### ISSUE THREAD

**Issue by aslagle** [NYPL-Simplified/web-reader-landing-page#71]
I think right now it only has index.html and index.css, but any other html pages you visit get added to the cache. We need to decide what all should be cached.

**Comment by EdwinGuzman** [comment]
This is what I see on prod:

```
CACHE MANIFEST
 #timestamp 2017-04-28 21:56:51.935396

index.html
about.html
404.html
privacypolicy.html
simplyE_logo.png
simplye.png
apple_badge.png
google_badge.png
amazon_badge.png
sw.js
webpub-viewer.js
require.js
fetch.js
main.css
iphone_simplyE.png
index.min.css
main.min.js

NETWORK:
*
```

It also has `main.min.js`. I'm currently working on removing the badge images from the repo. I think those basic pages (404, about, index, privacypolicy) should be in the manifest. Not sure about the pages in `/category/` or `/book_desc/` since they could potentially get updated often?

**Comment by aslagle** [comment]
Putting 404 in there would only mean it would work to go to 404.html when offline, but no one will do that. I like having the pages in category and book_desc link to the manifest but not be in it, so they get added when you visit them and then you can go back while offline, but you can't go to pages you haven't looked at yet.

**Comment by aslagle** [comment]
I'm not sure about cover images.

**Comment by EdwinGuzman** [comment]
According to the beginning of this: https://www.html5rocks.com/en/tutorials/appcache/beginner/

> The manifest attribute should be included on every page of your web application that you want cached. The browser does not cache a page if it does not contain the manifest attribute (unless it is explicitly listed in the manifest file itself. This means that any page the user navigates to that includes a manifest will be implicitly added to the application cache. Thus, there's no need to list every page in your manifest. If a page points to a manifest, there's no way to prevent this page being cached.

If that's the case then the link to the manifest file should be removed from the 404 page. The pages in the `/category/` and `/book_desc/` urls link to the manifest so they get cached too.
Navigation works well when I turn off my internet but not seeing images is annoying. Maybe we should cache that too but it may be too many images. I do like the fallback option and maybe it can be used to let users know, when they don't have internet access, that they can still browser their previous selections.

Is this the best tech to use right now? It's being deprecated: https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache
Maybe Service Workers can be an alternative?

For now, what do you think about removing the 404 page and adding the images?

**Comment by aslagle** [comment]
App cache is deprecated, but is still supported by all major browsers, whereas Service Workers aren't supported in iOS Safari yet. In the reader I use Service Workers if the browser supports it, but fall back to app cache if not. I think that's too much work to be worthwhile for the landing page.

It's a good idea to remove the 404 page, but I'm not sure what to do about the images. They'll fill up the app cache so you can't download as many books, and it would be hard to limit it to images on pages you've visited. Maybe we could have a single fallback image to show if you're offline.

**Comment by EdwinGuzman** [comment]
I like the idea of having a fallback image. I'll try that.

Great. I'll take a look at the SW code out of curiosity.
