### ISSUE TITLE
Render book length type

### ISSUE THREAD

**Issue by EdwinGuzman** [NYPL-Simplified/web-reader-landing-page#92]
From @kendraralston:
The delineations are
* Full novel
* Novel excerpt

There's a column in the spreadsheet "Short" which can be used but excepts are not currently being used. Short story/article and full novels are being used right now.

**Comment by jce1028** [comment]
Can we just say 
"Excerpt"  or "Book"

**Comment by kendraralston** [comment]
Sorry, that was working copy--not final. I'm working on finalizing it today. I do think "excerpt" is fine, but if we do use "novel", can we have another type for "short story" to incorporate those shorter reads that aren't excerpts or novels?

**Comment by kendraralston** [comment]
Novel
Excerpt
Short Story

**Comment by EdwinGuzman** [comment]
@leonardr @aslagle There's a "Short" column in the spreadsheet that I can use to differentiate a short story, but is there another flag to differentiate between "Novel" and "Excerpt"?

**Comment by kendraralston** [comment]
"Full Book" instead of "Novel" per Lynn/Gwen

**Comment by leonardr** [comment]
We can change the 'Short' column to a 'type' column that will directly contain the information you want.

Or you can look at the source. If the source is 'public domain' or 'plympton' then short pieces are Shorts and long pieces are Novels/Books. If the source is anything else, then short pieces are Excerpts and there will be no long pieces.

Let me know what you'd like.

**Comment by EdwinGuzman** [comment]
To not change the spreadsheet, I'll try the second option. Thanks.

**Comment by leonardr** [comment]
OK. Changing the spreadsheet is not a big deal, and we might want to do that later if this project continues and the data sources get more complicated.
